#!/usr/bin/env bash
# script that pings an IP address passed as an argument
# display it 5 times

if [ "$#" != 1 ]
then
    echo  "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$*"
fi
