#!/usr/bin/env bash
#fizz buzz task

for ((n=1; n<=100; n++))
do
    if (( n%3 == 0 )) && (( n%5 == 0 ))
    then  
    	  echo "FizzBuzz"
    elif (( n%5 == 0 ))
    then
	  echo "Buzz"
    elif (( n%3 == 0 ))
    then
	  echo "Fizz"
    else
	  echo "$n"
    fi
done