#!/usr/bin/env bash
# print numbers.
n=1;
while [ $n -le 20 ];
do
case $n in
        "9")	
		echo "$n"
		echo "bad luck from Japan"
         ;;
	"4")
		echo "$n"
		echo "bad luck from China"
	;;	
	"17")
		echo "$n"
		echo "bad luck from Italy"
	;;
	*)
	echo "$n"
	;;
esac
n=$((n+1))
done
