#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes.
x=0;
y=1;
while [ $x -le 12 ];
do
    echo "Hour: $x"		
    while [ $y -ne 60 ];
    do
	echo "$y"
	y=$((y+1))
    done
    x=$((x+1))
    y=1;
done
