#!/usr/bin/env bash
# Nginx is running as the nginx user
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# You cannot use apt-get remove
# Write a Bash script that configures the container to fit the above requirements

sudo pkill -9 apache2
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 700 /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo service nginx start
